<a href="https://colab.research.google.com/github/Ninja-draw-coder/PythonProjects/blob/main/np_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Arithmetic operations on single nad multidimensional

import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c= np.array(["a","b","c"])
d = np.array(["1","2"],dtype ="str")





print(a+b)  # 6, 8 , 10, 12
print(d)
print(c)

[ 6  8 10 12]
['1' '2']
['a' 'b' 'c']


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

'''print(a)
print(b)'''

print(a+b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [ ]:
a = np.array([[[1,2],[3,4],[5,6]]])
b = np.array([[[5,6],[7,8],[0,9]]])

'''print(a)
print(b)'''

print(a+b)
print(a*b)

[[[ 6  8]
  [10 12]
  [ 5 15]]]
[[[ 5 12]
  [21 32]
  [ 0 54]]]


In [ ]:
#reshape() function -> used to change the shape of an array without changing its data

# np.reshape(array,new_shape)

arr = np.array([1,2,3,4,5,6,7,8,9])   #1D  with 9 elements

re_arr = arr.reshape(3,3)
print(re_arr)

re_arr2 = arr.reshape(1,9)
print(re_arr2)

re_arr3 = arr.reshape(9,2)
print(re_arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


ValueError: cannot reshape array of size 9 into shape (9,2)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
re = arr.reshape(5,2,1)
print(re)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]


In [ ]:
#Matrix product

'''3x4  -> 3rows, 4 columns
   4x5  -> 4 rows, 5 columns

   The number of columns in first matrix should be to
   the number of rows  in second matrix

   the answer will be in shape 3x5 -> 3 rows and 5 columns

   but if i have matrices like

   4x5 dot product 3x4   not possible because no.of columns in first is not equals to no of rows in second'''


a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])  #3x4

b = np.array([[1,2,3,4,5],[6,7,8,9,8],[4,5,6,7,8],[2,3,4,5,6]])  #4x5

'''print(a.shape)
print(b.shape)

print(a)
print(b)'''

print(np.dot(a,b))
print(b.dot(a))  #4x5 and 3x4

[[ 33  43  53  63  69]
 [ 85 111 137 163 177]
 [ 97 127 157 187 201]]


ValueError: shapes (4,5) and (3,4) not aligned: 5 (dim 1) != 3 (dim 0)

In [ ]:
'''Numpy offers powerful functions
1. Universal functions -> operates element wise on array making calculations fast and efficent
np.mod()   -> remainder
np.log()   -> natural logarithm value
np.bitwise_and()  -> bitwise AND operation
np.hypot() -> hypotenuse of right triangle   (square root of (base^2 + height^2))

2. Aggregate functions
3. Logic functions
4. Element-wise comparison functions'''



In [ ]:
#mod()
print(np.mod([1,2,3,4],3))

#log()
print(np.log([1,2,3,4]))   #natural logarithm

#log2()
print(np.log2([1,2,3,4]))  #logarithm with base 2

#log10()
print(np.log10([1,2,3,4])) #logarithm with base 10

#bitwise_and()
print(np.bitwise_and([1,2,3,4],[3,4,5,6]))

#hypot()
print(np.hypot(3,4))  #3 is base, 4 is height

[1 2 0 1]
[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]
[1 0 1 4]
5.0
