<a href="https://colab.research.google.com/github/Ninja-draw-coder/PythonProjects/blob/main/numpyDIYModule8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.arange(15)
b= np.split(a,3)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]


In [8]:
import numpy as np
a = np.arange(16).reshape(4,4)
b = np.hsplit(a,2)
print(b)
#print(c)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [9]:
import numpy as np
a =np.arange(20).reshape(4,5)
print(a)
b= np.transpose(a)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [26]:
import numpy as np
a = np.array([1,2,3,4])
b= np.array([6,7,8,9])
print(a,b)
a=np.reshape(a,(2,2))
b=np.reshape(b,(2,2))
print("hstack Output horizontally stacked array:\n ")
print(np.hstack((a,b)))
print("vstack Output vertically stacked array:\n")
print(np.vstack((a,b)))
print("concatnate")
print(np.concatenate((a,b),axis=0))
print("split")
print(np.split(np.vstack((a,b)),1))

[1 2 3 4] [6 7 8 9]
hstack Output horizontally stacked array:
 
[[1 2 6 7]
 [3 4 8 9]]
vstack Output vertically stacked array:

[[1 2]
 [3 4]
 [6 7]
 [8 9]]
concatnate
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
split
[array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])]
